language: go
go:
- '1.10'
deploy:
  provider: releases
  api_key:
    secure: tRoe90iEct050/XQcQ1oS1Wm5Yl2V+t8K1I1Hy66aWHoGf6NRxk9VRlKyg/Fr21pcZ4vhKwtH6dvTUhKPM8TtaUf1oC1wlwZnsq2oIEAuxRMh3bCd7Psyycmd5Oo8bF3gQ0FXmpwXSDh8D8qXjx190GyP+4lV0mSehWxOv+hM4ob7v19iUmkqL3EbJonTu+weDweuAUpZsfuODUYp12vT6uRFeN85RlJccOWvTstj1W6uiycDfjDTU3N2/PmTkohQmG8JSrDZ03+89pzkTfNUGWT/y9mNsGrMlKtTIJ+tcKEuzY+pUEIooxuB9y/np3EJyfCLE/MPrMz1kxkWfn++4wkQ/C8u7KiaPC9XDF9CfOEAa7SStlx+WsezSeqCHkPYuOEFEIdXOCrlmUWwHnOjqIlYT76fOUl2mQ1MMGc/eXYS91GBu2GinRK9XrC4O3Y2+FDFhDRBoWZAXoPgjkIocae/CI2/nnD6uQ1YhJy77tbdDzrlLykXpqSeiHuzNfVTfPE+9YJfnAPq2aUjvYCHE7sKnyAIeEQJxDGGzO7erVO6UJJYRo+B2QKbgxzFSaZup+0qFMkZrrakdIS4iFyrzi0INcIKGDNyejgXAbuoYhRxYzKu3ywsM8HG+ykK3wC6dpIarwKywJhDYPsjYSnu3n060bqzo1nd+yuJaXg6+E=
  file: terraform-provider-phpipam
  skip_cleanup: true
  on:
    repo: Ouest-France/terraform-provider-phpipam
    branch: master
    tags: true
